/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "udsevdmyhyehwbkyrzrb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkc2V2ZG15aHllaHdia3lyenJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDAyMzQsImV4cCI6MjA3MDMxNjIzNH0.8KowVeQCZpvXq9KDB2g3WlsuUv-IwEzdikfdfOImaAw"
